version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanghan_pos
    restart: unless-stopped
    ports:
      - "3006:3000"
    environment:
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@host.docker.internal:3306/kanghan_pos
      JWT_SECRET: ${JWT_SECRET}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      NODE_ENV: production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        node server.js
      "
